Action()
{
	
	//web_set_certificate_ex("CertFilePath=\\internal.vic.gov.au\\DHHS\\HomeDirs4\\ssen3107\\Desktop\\PSErootCA.crt",LAST);
	//web_set_certificate_ex("CertFilePath=C:\\Data\\FSV\\API_Artifacts\\API_Artifacts\\sit.pfx",LAST);

	web_set_sockets_option("SSL_VERSION", "TLS1.2");

	web_set_certificate_ex("CertFilePath=C:\\Data\\FSV\\API_Artifacts\\API_Artifacts\\sit.pem",
		 "CertFormat=PEM",
		 "KeyFilePath=C:\\Data\\FSV\\API_Artifacts\\API_Artifacts\\sit.pem",
		 "KeyFormat=PEM",
		 "Password=password01",
		 //"CertIndex=1",
		 LAST);
		 
	web_set_sockets_option("SSL_VERSION", "2&3");
	
	//web_set_sockets_option("SSL_VERSION", "TLS1.2");

	web_add_header("Proxy-Authorization","Basic a2xhdTEyMDU6S2wyODI4MjghJg==");
	web_add_header("Authorization","Basic a2xhdTEyMDU6S2wyODI4MjghJg==");
	
	web_custom_request("start.swe_63",
		"URL=https://{param_Domain}/eai_anon_enu/start.swe?SWEExtSource=SecureWebService&SWEExtCmd=Execute&WSSOAP=1",
		"Method=POST",
		"Referer=", 
	    "Snapshot=t1.inf", 
	    "Mode=URL", 
	    "EncType=text/xml; charset=utf-8", 
		"Body=<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
			"<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:sieb=\"http://siebel.com.L17Incident\" xmlns:dhs=\"http://www.siebel.com/xml/DHSL17%20Incident\">"
			   "<soapenv:Header>"
			   "<wsse:Security xmlns:wsse=\"http://schemas.xmlsoap.org/ws/2002/04/secext\">"
				"<wsse:UsernameToken>"
					"<wsse:Username>VPUSER1</wsse:Username>"
					"<wsse:Password Type=\"wsse:PasswordText\">VPUS3R@123</wsse:Password>"
					"<wsse:SessionType xmlns=\"http://siebel.com/webservices\">None</wsse:SessionType>"
				"</wsse:UsernameToken>"
			   "</wsse:Security>"
			 "</soapenv:Header>"
			   "<soapenv:Body>"
			      "<sieb:IncidentInsert>"
					"<PoliceInputString><![CDATA[<?xml version=\"1.0\" encoding=\"utf-8\"?>"
					"<ChildReferral xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">"
						"<ReferralChildren>"
							"<ReferralChild>"
								"<InvolveDescCd>CHP</InvolveDescCd>"
								"<ReportedFamilyName>Poey</ReportedFamilyName>"
								"<ReportedFirstName>Marcus</ReportedFirstName>"
								"<GivenName>Marcus</GivenName>"
								"<ReportedDob>20010207</ReportedDob>"
								"<ReportedSex>F</ReportedSex>"
								"<ResideWith>1</ResideWith>"
								"<ReportedIndigenousStatus>TSI</ReportedIndigenousStatus>"
								"<Uid>49896255</Uid>"
							"</ReferralChild>"
						"</ReferralChildren>"
						"<ReferralMOs>"
							"<ReferralMO>"
								"<GroupId>1</GroupId>"
								"<GroupDesc>Criminal Abuse</GroupDesc>"
								"<GroupCodeId>21</GroupCodeId>"
								"<Code>1</Code>"
								"<SubCode>79</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Physical (Indictable)</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>1</GroupId>"
								"<GroupDesc>Criminal Abuse</GroupDesc>"
								"<GroupCodeId>21</GroupCodeId>"
								"<Code>2</Code>"
								"<SubCode>79</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Physical (Summary)</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>1</GroupId>"
								"<GroupDesc>Criminal Abuse</GroupDesc>"
								"<GroupCodeId>21</GroupCodeId>"
								"<Code>3</Code>"
								"<SubCode>79</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Sexual</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>1</GroupId>"
								"<GroupDesc>Criminal Abuse</GroupDesc>"
								"<GroupCodeId>21</GroupCodeId>"
								"<Code>4</Code>"
								"<SubCode>79</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Threats</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>1</GroupId>"
								"<GroupDesc>Criminal Abuse</GroupDesc>"
								"<GroupCodeId>21</GroupCodeId>"
								"<Code>5</Code>"
								"<SubCode>79</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Pet Abuse</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>1</GroupId>"
								"<GroupDesc>Criminal Abuse</GroupDesc>"
								"<GroupCodeId>21</GroupCodeId>"
								"<Code>6</Code>"
								"<SubCode>79</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Other</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>1</GroupId>"
								"<GroupDesc>Criminal Abuse</GroupDesc>"
								"<GroupCodeId>21</GroupCodeId>"
								"<Code>7</Code>"
								"<SubCode>79</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Damage (Indictable)</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>1</GroupId>"
								"<GroupDesc>Criminal Abuse</GroupDesc>"
								"<GroupCodeId>21</GroupCodeId>"
								"<Code>8</Code>"
								"<SubCode>79</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Damage (Summary)</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>1</GroupId>"
								"<GroupDesc>Criminal Abuse</GroupDesc>"
								"<GroupCodeId>21</GroupCodeId>"
								"<Code>9</Code>"
								"<SubCode>79</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Theft</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>1</GroupId>"
								"<GroupDesc>Criminal Abuse</GroupDesc>"
								"<GroupCodeId>21</GroupCodeId>"
								"<Code>10</Code>"
								"<SubCode>79</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Stalking - Less Than 2 Weeks</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>1</GroupId>"
								"<GroupDesc>Criminal Abuse</GroupDesc>"
								"<GroupCodeId>21</GroupCodeId>"
								"<Code>11</Code>"
								"<SubCode>79</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Stalking - B/W 2 And 4 Weeks</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>1</GroupId>"
								"<GroupDesc>Criminal Abuse</GroupDesc>"
								"<GroupCodeId>21</GroupCodeId>"
								"<Code>12</Code>"
								"<SubCode>79</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Stalking - More Than 4 Weeks</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>1</GroupId>"
								"<GroupDesc>Criminal Abuse</GroupDesc>"
								"<GroupCodeId>21</GroupCodeId>"
								"<Code>13</Code>"
								"<SubCode>79</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Breach Only</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>1</GroupId>"
								"<GroupDesc>Criminal Abuse</GroupDesc>"
								"<GroupCodeId>21</GroupCodeId>"
								"<Code>14</Code>"
								"<SubCode>79</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Breach And Other</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>1</GroupId>"
								"<GroupDesc>Non Criminal Abuse</GroupDesc>"
								"<GroupCodeId>21</GroupCodeId>"
								"<Code>15</Code>"
								"<SubCode>79</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Emotional</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>1</GroupId>"
								"<GroupDesc>Non Criminal Abuse</GroupDesc>"
								"<GroupCodeId>21</GroupCodeId>"
								"<Code>16</Code>"
								"<SubCode>79</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Verbal</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>1</GroupId>"
								"<GroupDesc>Non Criminal Abuse</GroupDesc>"
								"<GroupCodeId>21</GroupCodeId>"
								"<Code>17</Code>"
								"<SubCode>79</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Social</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>1</GroupId>"
								"<GroupDesc>Non Criminal Abuse</GroupDesc>"
								"<GroupCodeId>21</GroupCodeId>"
								"<Code>18</Code>"
								"<SubCode>79</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Economic</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>1</GroupId>"
								"<GroupDesc>Non Criminal Abuse</GroupDesc>"
								"<GroupCodeId>21</GroupCodeId>"
								"<Code>19</Code>"
								"<SubCode>79</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Spiritual</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>1</GroupId>"
								"<GroupDesc>Non Criminal Abuse</GroupDesc>"
								"<GroupCodeId>21</GroupCodeId>"
								"<Code>20</Code>"
								"<SubCode>79</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Non Violent Non Abusive</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>3</GroupId>"
								"<GroupDesc>AFM/Other Party Relationship</GroupDesc>"
								"<GroupCodeId>22</GroupCodeId>"
								"<Code>1</Code>"
								"<SubCode>96</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Married</CodeDesc>"
								"<SubIncidentId>0</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>3</GroupId>"
								"<GroupDesc>AFM/Other Party Relationship</GroupDesc>"
								"<GroupCodeId>23</GroupCodeId>"
								"<Code>2</Code>"
								"<SubCode>96</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>De-Facto</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>3</GroupId>"
								"<GroupDesc>AFM/Other Party Relationship</GroupDesc>"
								"<GroupCodeId>24</GroupCodeId>"
								"<Code>3</Code>"
								"<SubCode>96</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Child/Parent</CodeDesc>"
								"<SubIncidentId>0</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>3</GroupId>"
								"<GroupDesc>AFM/Other Party Relationship</GroupDesc>"
								"<GroupCodeId>25</GroupCodeId>"
								"<Code>4</Code>"
								"<SubCode>96</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Separated</CodeDesc>"
								"<SubIncidentId>0</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>3</GroupId>"
								"<GroupDesc>AFM/Other Party Relationship</GroupDesc>"
								"<GroupCodeId>26</GroupCodeId>"
								"<Code>5</Code>"
								"<SubCode>96</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Divorced</CodeDesc>"
								"<SubIncidentId>0</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>3</GroupId>"
								"<GroupDesc>AFM/Other Party Relationship</GroupDesc>"
								"<GroupCodeId>27</GroupCodeId>"
								"<Code>7</Code>"
								"<SubCode>96</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Other Family Member</CodeDesc>"
								"<SubIncidentId>0</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>3</GroupId>"
								"<GroupDesc>AFM/Other Party Relationship</GroupDesc>"
								"<GroupCodeId>28</GroupCodeId>"
								"<Code>9</Code>"
								"<SubCode>96</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Boyfriend/Girlfriend</CodeDesc>"
								"<SubIncidentId>0</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>3</GroupId>"
								"<GroupDesc>AFM/Other Party Relationship</GroupDesc>"
								"<GroupCodeId>29</GroupCodeId>"
								"<Code>10</Code>"
								"<SubCode>96</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Same Sex (Gay)</CodeDesc>"
								"<SubIncidentId>0</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>3</GroupId>"
								"<GroupDesc>AFM/Other Party Relationship</GroupDesc>"
								"<GroupCodeId>30</GroupCodeId>"
								"<Code>11</Code>"
								"<SubCode>96</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Same Sex (Lesbian)</CodeDesc>"
								"<SubIncidentId>0</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>3</GroupId>"
								"<GroupDesc>AFM/Other Party Relationship</GroupDesc>"
								"<GroupCodeId>31</GroupCodeId>"
								"<Code>12</Code>"
								"<SubCode>96</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Carer</CodeDesc>"
								"<SubIncidentId>0</SubIncidentId>"
							"</ReferralMO>"    
							"<ReferralMO>"
								"<GroupId>6</GroupId>"
								"<GroupDesc>Vulnerability Factors for AFM</GroupDesc>"
								"<GroupCodeId>56</GroupCodeId>"
								"<Code>02</Code>"
								"<SubCode>83</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Depression/Mental Health Issue</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>6</GroupId>"
								"<GroupDesc>Vulnerability Factors for AFM</GroupDesc>"
								"<GroupCodeId>57</GroupCodeId>"
								"<Code>03</Code>"
								"<SubCode>83</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Suicidal Ideas Or Attempts</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>6</GroupId>"
								"<GroupDesc>Vulnerability Factors for AFM</GroupDesc>"
								"<GroupCodeId>58</GroupCodeId>"
								"<Code>04</Code>"
								"<SubCode>83</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Isolation</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>6</GroupId>"
								"<GroupDesc>Vulnerability Factors for AFM</GroupDesc>"
								"<GroupCodeId>59</GroupCodeId>"
								"<Code>05</Code>"
								"<SubCode>83</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Alcohol Possible</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>6</GroupId>"
								"<GroupDesc>Vulnerability Factors for AFM</GroupDesc>"
								"<GroupCodeId>60</GroupCodeId>"
								"<Code>06</Code>"
								"<SubCode>83</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Alcohol Definite</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>6</GroupId>"
								"<GroupDesc>Vulnerability Factors for AFM</GroupDesc>"
								"<GroupCodeId>61</GroupCodeId>"
								"<Code>07</Code>"
								"<SubCode>83</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Drugs Possible</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>6</GroupId>"
								"<GroupDesc>Vulnerability Factors for AFM</GroupDesc>"
								"<GroupCodeId>62</GroupCodeId>"
								"<Code>08</Code>"
								"<SubCode>83</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Drugs Definite</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>6</GroupId>"
								"<GroupDesc>Vulnerability Factors for AFM</GroupDesc>"
								"<GroupCodeId>63</GroupCodeId>"
								"<Code>09</Code>"
								"<SubCode>83</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Other Substances</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>7</GroupId>"
								"<GroupDesc>Vulnerability Factors (Others)</GroupDesc>"
								"<GroupCodeId>64</GroupCodeId>"
								"<Code>01</Code>"
								"<SubCode>84</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Separation</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>7</GroupId>"
								"<GroupDesc>Vulnerability Factors (Others)</GroupDesc>"
								"<GroupCodeId>65</GroupCodeId>"
								"<Code>02</Code>"
								"<SubCode>84</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Escalation - Increase Sev/Freq</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>7</GroupId>"
								"<GroupDesc>Vulnerability Factors (Others)</GroupDesc>"
								"<GroupCodeId>66</GroupCodeId>"
								"<Code>03</Code>"
								"<SubCode>84</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Presence Of A Disability</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>7</GroupId>"
								"<GroupDesc>Vulnerability Factors (Others)</GroupDesc>"
								"<GroupCodeId>67</GroupCodeId>"
								"<Code>04</Code>"
								"<SubCode>84</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Financial Difficulties</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>7</GroupId>"
								"<GroupDesc>Vulnerability Factors (Others)</GroupDesc>"
								"<GroupCodeId>140</GroupCodeId>"
								"<Code>05</Code>"
								"<SubCode>84</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Pregnancy/New Birth</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>9</GroupId>"
								"<GroupDesc>Vulnerability Factors for Perp</GroupDesc>"
								"<GroupCodeId>73</GroupCodeId>"
								"<Code>01</Code>"
								"<SubCode>85</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Harm Or Threat Harm Victim</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>9</GroupId>"
								"<GroupDesc>Vulnerability Factors for Perp</GroupDesc>"
								"<GroupCodeId>74</GroupCodeId>"
								"<Code>02</Code>"
								"<SubCode>85</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Tried To Choke Victim</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>9</GroupId>"
								"<GroupDesc>Vulnerability Factors for Perp</GroupDesc>"
								"<GroupCodeId>75</GroupCodeId>"
								"<Code>03</Code>"
								"<SubCode>85</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Threaten To Kill Victim</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>9</GroupId>"
								"<GroupDesc>Vulnerability Factors for Perp</GroupDesc>"
								"<GroupCodeId>76</GroupCodeId>"
								"<Code>04</Code>"
								"<SubCode>85</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Harm/Threat Harm/Kill Children</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>9</GroupId>"
								"<GroupDesc>Vulnerability Factors for Perp</GroupDesc>"
								"<GroupCodeId>77</GroupCodeId>"
								"<Code>05</Code>"
								"<SubCode>85</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Harm/Threat Harm/Kill Family</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>9</GroupId>"
								"<GroupDesc>Vulnerability Factors for Perp</GroupDesc>"
								"<GroupCodeId>78</GroupCodeId>"
								"<Code>06</Code>"
								"<SubCode>85</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Harm/Threat Harm/Kill Pets</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>9</GroupId>"
								"<GroupDesc>Vulnerability Factors for Perp</GroupDesc>"
								"<GroupCodeId>79</GroupCodeId>"
								"<Code>07</Code>"
								"<SubCode>85</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Threaten/Attempt Suicide</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>9</GroupId>"
								"<GroupDesc>Vulnerability Factors for Perp</GroupDesc>"
								"<GroupCodeId>80</GroupCodeId>"
								"<Code>08</Code>"
								"<SubCode>85</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Stalking Of Victim</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>9</GroupId>"
								"<GroupDesc>Vulnerability Factors for Perp</GroupDesc>"
								"<GroupCodeId>81</GroupCodeId>"
								"<Code>09</Code>"
								"<SubCode>85</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Sexual Assault Of Victim</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>9</GroupId>"
								"<GroupDesc>Vulnerability Factors for Perp</GroupDesc>"
								"<GroupCodeId>82</GroupCodeId>"
								"<Code>11</Code>"
								"<SubCode>85</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Controlling Behaviours</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>9</GroupId>"
								"<GroupDesc>Vulnerability Factors for Perp</GroupDesc>"
								"<GroupCodeId>83</GroupCodeId>"
								"<Code>12</Code>"
								"<SubCode>85</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Unemployed</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>9</GroupId>"
								"<GroupDesc>Vulnerability Factors for Perp</GroupDesc>"
								"<GroupCodeId>84</GroupCodeId>"
								"<Code>13</Code>"
								"<SubCode>85</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Depression/Mental Health Issue</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>9</GroupId>"
								"<GroupDesc>Vulnerability Factors for Perp</GroupDesc>"
								"<GroupCodeId>85</GroupCodeId>"
								"<Code>15</Code>"
								"<SubCode>85</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Alcohol Possible</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>9</GroupId>"
								"<GroupDesc>Vulnerability Factors for Perp</GroupDesc>"
								"<GroupCodeId>86</GroupCodeId>"
								"<Code>16</Code>"
								"<SubCode>85</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Alcohol Definite</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>9</GroupId>"
								"<GroupDesc>Vulnerability Factors for Perp</GroupDesc>"
								"<GroupCodeId>87</GroupCodeId>"
								"<Code>17</Code>"
								"<SubCode>85</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Drugs Possible</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>9</GroupId>"
								"<GroupDesc>Vulnerability Factors for Perp</GroupDesc>"
								"<GroupCodeId>88</GroupCodeId>"
								"<Code>18</Code>"
								"<SubCode>85</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Drugs Definite</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>9</GroupId>"
								"<GroupDesc>Vulnerability Factors for Perp</GroupDesc>"
								"<GroupCodeId>89</GroupCodeId>"
								"<Code>19</Code>"
								"<SubCode>85</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Other Substances</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"    
							"<ReferralMO>"
								"<GroupId>10</GroupId>"
								"<GroupDesc>Vulnerability Factors for Perp (FireArms)</GroupDesc>"
								"<GroupCodeId>92</GroupCodeId>"
								"<Code>04</Code>"
								"<SubCode>86</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Firearm(s) Threatened/Used</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>10</GroupId>"
								"<GroupDesc>Vulnerability Factors for Perp (FireArms)</GroupDesc>"
								"<GroupCodeId>92</GroupCodeId>"
								"<Code>04</Code>"
								"<SubCode>86</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Firearm(s) Threatened</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>12</GroupId>"
								"<GroupDesc>Risk Management Strategy (Civil Action)</GroupDesc>"
								"<GroupCodeId>116</GroupCodeId>"
								"<Code>48</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Fvsn Issued</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>12</GroupId>"
								"<GroupDesc>Risk Management Strategy (Civil Action)</GroupDesc>"
								"<GroupCodeId>126</GroupCodeId>"
								"<Code>49</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>AFM Applying For Fvio</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>12</GroupId>"
								"<GroupDesc>Risk Management Strategy (Civil Action)</GroupDesc>"
								"<GroupCodeId>119</GroupCodeId>"
								"<Code>53</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Police Applying Via A&amp;S</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>12</GroupId>"
								"<GroupDesc>Risk Management Strategy (Civil Action)</GroupDesc>"
								"<GroupCodeId>118</GroupCodeId>"
								"<Code>57</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Police Applying For Intrm I/O</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>12</GroupId>"
								"<GroupDesc>Risk Management Strategy (Civil Action)</GroupDesc>"
								"<GroupCodeId>117</GroupCodeId>"
								"<Code>61</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Police Applying Via A&amp;W</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>12</GroupId>"
								"<GroupDesc>Risk Management Strategy (Civil Action)</GroupDesc>"
								"<GroupCodeId>115</GroupCodeId>"
								"<Code>86</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Exclusion Conditions Used</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>12</GroupId>"
								"<GroupDesc>Risk Management Strategy (Civil Action)</GroupDesc>"
								"<GroupCodeId>127</GroupCodeId>"
								"<Code>90</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Fvio Variation Required</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>13</GroupId>"
								"<GroupDesc>Risk Management Strategy (Criminal Action)</GroupDesc>"
								"<GroupCodeId>122</GroupCodeId>"
								"<Code>77</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Charges Pending (Breach I/O)</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>13</GroupId>"
								"<GroupDesc>Risk Management Strategy (Criminal Action)</GroupDesc>"
								"<GroupCodeId>123</GroupCodeId>"
								"<Code>81</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Charges Pending (Other)</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>13</GroupId>"
								"<GroupDesc>Risk Management Strategy (Criminal Action)</GroupDesc>"
								"<GroupCodeId>121</GroupCodeId>"
								"<Code>85</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Charges Pending (Breach &amp; Oth)</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>13</GroupId>"
								"<GroupDesc>Risk Management Strategy (Criminal Action)</GroupDesc>"
								"<GroupCodeId>124</GroupCodeId>"
								"<Code>89</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Offender Bailed With Cond</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>13</GroupId>"
								"<GroupDesc>Risk Management Strategy (Criminal Action)</GroupDesc>"
								"<GroupCodeId>125</GroupCodeId>"
								"<Code>93</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Remanded In Custody</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>14</GroupId>"
								"<GroupDesc>Risk Management Strategy (Other Action)</GroupDesc>"
								"<GroupCodeId>111</GroupCodeId>"
								"<Code>46</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Holding Pwrs (Direction) Used</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>14</GroupId>"
								"<GroupDesc>Risk Management Strategy (Other Action)</GroupDesc>"
								"<GroupCodeId>112</GroupCodeId>"
								"<Code>47</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Holding Pwrs (Detention) Used</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>14</GroupId>"
								"<GroupDesc>Risk Management Strategy (Other Action)</GroupDesc>"
								"<GroupCodeId>113</GroupCodeId>"
								"<Code>65</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Weapon/S &amp;/Or Firearms Seized</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>14</GroupId>"
								"<GroupDesc>Risk Management Strategy (Other Action)</GroupDesc>"
								"<GroupCodeId>439</GroupCodeId>"
								"<Code>73</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Firearm(s) Licence Revoc Pend</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>14</GroupId>"
								"<GroupDesc>Risk Management Strategy (Other Action)</GroupDesc>"
								"<GroupCodeId>114</GroupCodeId>"
								"<Code>94</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Firearms Only Seized</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>14</GroupId>"
								"<GroupDesc>Risk Management Strategy (Other Action)</GroupDesc>"
								"<GroupCodeId>128</GroupCodeId>"
								"<Code>95</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Weapons Only Seized</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>" 
							"<ReferralMO>"
								"<GroupId>15</GroupId>"
								"<GroupDesc>Risk Management Strategy (Referral Action)</GroupDesc>"
								"<GroupCodeId>103</GroupCodeId>"
								"<Code>91</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Recommended High Risk Client</CodeDesc>"
								"<SubIncidentId>0</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>15</GroupId>"
								"<GroupDesc>Risk Management Strategy (Referral Action)</GroupDesc>"
								"<GroupCodeId>104</GroupCodeId>"
								"<Code>29</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Wdvcs Immediate Assist (24/7)</CodeDesc>"
								"<SubIncidentId>0</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>15</GroupId>"
								"<GroupDesc>Risk Management Strategy (Referral Action)</GroupDesc>"
								"<GroupCodeId>105</GroupCodeId>"
								"<Code>25</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Formal Referral For AFM</CodeDesc>"
								"<SubIncidentId>1</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>15</GroupId>"
								"<GroupDesc>Risk Management Strategy (Referral Action)</GroupDesc>"
								"<GroupCodeId>106</GroupCodeId>"
								"<Code>37</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Formal Referral Perpetrator</CodeDesc>"
								"<SubIncidentId>0</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>15</GroupId>"
								"<GroupDesc>Risk Management Strategy (Referral Action)</GroupDesc>"
								"<GroupCodeId>107</GroupCodeId>"
								"<Code>21</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Informal Referral For AFM</CodeDesc>"
								"<SubIncidentId>0</SubIncidentId>"
							"</ReferralMO>"   
							"<ReferralMO>"
								"<GroupId>15</GroupId>"
								"<GroupDesc>Risk Management Strategy (Referral Action)</GroupDesc>"
								"<GroupCodeId>108</GroupCodeId>"
								"<Code>33</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Informal Referral Perpetrator</CodeDesc>"
								"<SubIncidentId>0</SubIncidentId>"
							"</ReferralMO>"
							"<ReferralMO>"
								"<GroupId>15</GroupId>"
								"<GroupDesc>Risk Management Strategy (Referral Action)</GroupDesc>"
								"<GroupCodeId>436</GroupCodeId>"
								"<Code>41</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Notify Child Protection (Dhs)</CodeDesc>"
								"<SubIncidentId>0</SubIncidentId>"
							"</ReferralMO>"    
							"<ReferralMO>"
								"<GroupId>15</GroupId>"
								"<GroupDesc>Risk Management Strategy (Referral Action)</GroupDesc>"
								"<GroupCodeId>438</GroupCodeId>"
								"<Code>92</Code>"
								"<SubCode>89</SubCode>"
								"<Mk2CodeDesc />"
								"<CodeDesc>Child First</CodeDesc>"
								"<SubIncidentId>0</SubIncidentId>"
							"</ReferralMO>"
						"</ReferralMOs>"
						"<FVPilotMOs />"
						"<ReportDetail>"
							"<ReportID>FSV-{param_AFMID}</ReportID>"
							"<IncidentID>Selva-{param_AFMID}</IncidentID>"
							"<ResponseZone>WGL</ResponseZone>"
							"<StartingPointCode>03</StartingPointCode>"    
							"<rep_member_rank>SCONST</rep_member_rank>"
							"<rep_member_lastname>Ladd</rep_member_lastname>"
							"<rep_member_firstname>David</rep_member_firstname>"
							"<rep_member_involve_cd>REP</rep_member_involve_cd>"
							"<rep_member_vpnumber>k900184</rep_member_vpnumber>"
							"<ReportTm>{param_Time1}</ReportTm>"
							"<ReportDt>{param_Date}T{param_Time}</ReportDt>"
							"<MemberStnCd>EWHDSK</MemberStnCd>"
							"<MemberStnDesc>EWHDSK</MemberStnDesc>"
							"<CommittedBetween>true</CommittedBetween>"
							"<CommitFromDt>{param_Date}T{param_Time}</CommitFromDt>"
							"<CommitFromTm>{param_Time1}</CommitFromTm>"
							"<CommitToDt>{param_Date}T{param_Time2}</CommitToDt>"
							"<CommitToTm>{param_Time4}</CommitToTm>"
							"<StreetNoType>No</StreetNoType>"
							"<StreetName>Railway</StreetName>"
							"<StreetType>TCE</StreetType>"
							"<Town>Geelong</Town>"
							"<State>VIC</State>"
							"<Postcode>3220</Postcode>"
							"<CaseNarrative>AFM and Respondent have been married for 12 years. The couple live together and have 2 children.  Approximately one week ago a verbal argument started between the pair regarding the Respondent being unhappy with what the AFM had or hadn't done that day. The verbal dispute escalated and resulted in the Respondent shoving the AFM in the chest with both hands.</CaseNarrative>"    
							"<AFMFamilyName>George</AFMFamilyName>"
							"<AFMFirstName>Mike</AFMFirstName>"
							"<AFMSecondName>K.K.</AFMSecondName>"
							"<AfmUid>989763806</AfmUid>"
							"<AFMDOB>20010207</AFMDOB>"
							"<AFMSex>F</AFMSex>"
							"<AFMAge>56</AFMAge>"
							"<AFMEthnicCode>CAU</AFMEthnicCode>"
							"<AFMIndigenousStatus>ABL</AFMIndigenousStatus>"
							"<AFMContactPreference>0</AFMContactPreference>"
							"<AFMSocialMediaDt1>0001-01-01T00:00:00</AFMSocialMediaDt1>"
							"<AFMSocialMediaDt2>0001-01-01T00:00:00</AFMSocialMediaDt2>"
							"<AFMSocialMediaDt3>0001-01-01T00:00:00</AFMSocialMediaDt3>"
							"<AFMPhonePreference>0</AFMPhonePreference>"
							"<AFMPhoneTypeCd1>M</AFMPhoneTypeCd1>"
							"<AFMPhoneNo1>0412345678</AFMPhoneNo1>"
							"<AFMPhoneTypeCd2>B</AFMPhoneTypeCd2>"
							"<AFMPhoneNo2>0487654321</AFMPhoneNo2>"
							"<AFMPhoneTypeCd3>O</AFMPhoneTypeCd3>"
							"<AFMPhoneNo3>0445612378</AFMPhoneNo3>"
							"<AfmContactAnyTmIn>true</AfmContactAnyTmIn>"
							"<AfmReferAttCd>2</AfmReferAttCd>"
							"<AfmATSIReferralPref>2</AfmATSIReferralPref>"
							"<AFMStreetNoType>AV</AFMStreetNoType>"
							"<AFMStreetNo>88</AFMStreetNo>"
							"<AFMStreetName>Rich Valley</AFMStreetName>"
							"<AFMStreetType>AVE</AFMStreetType>"
							"<AFMTown>Caulfield</AFMTown>"
							"<AFMState>VIC</AFMState>"
							"<AFMPostcode>3162</AFMPostcode>"
							"<AfmOtherAccomIn>false</AfmOtherAccomIn>"    
							"<ChildPresentNo>0</ChildPresentNo>"    
							"<PerpFamilyName>Mighty</PerpFamilyName>"
							"<PerpFirstName>Bruce</PerpFirstName>"
							"<PerpSecondName>Al</PerpSecondName>"
							"<PerpUid>1234555</PerpUid>"
							"<PerpDOB>20010207</PerpDOB>"
							"<PerpAge>25</PerpAge>"
							"<PerpEthnicCode>CAU</PerpEthnicCode>"
							"<PerpIndigenousStatus>NAT</PerpIndigenousStatus>"
							"<PerpSex>M</PerpSex>"
							"<PerpContactPreference>0</PerpContactPreference>"
							"<PerpPhonePreference>0</PerpPhonePreference>"
							"<PerpPhoneTypeCd1>M</PerpPhoneTypeCd1>"
							"<PerpPhoneNo1>0412345678</PerpPhoneNo1>"
							"<PerpPhoneTypeCd2>B</PerpPhoneTypeCd2>"
							"<PerpPhoneNo2>0487654321</PerpPhoneNo2>"
							"<PerpPhoneTypeCd3>O</PerpPhoneTypeCd3>"
							"<PerpPhoneNo3>0445612378</PerpPhoneNo3>"
							"<PerpContactAnyTmIn>true</PerpContactAnyTmIn>"
							"<PerpSocialMediaDt1>0001-01-01T00:00:00</PerpSocialMediaDt1>"
							"<PerpSocialMediaDt2>0001-01-01T00:00:00</PerpSocialMediaDt2>"
							"<PerpSocialMediaDt3>0001-01-01T00:00:00</PerpSocialMediaDt3>"
							"<PerpReferAttCd>2</PerpReferAttCd>"
							"<PerpATSIReferralPref>1</PerpATSIReferralPref>"
							"<PerpStreetNo>88</PerpStreetNo>"
							"<PerpStreetNoType>S</PerpStreetNoType>"
							"<PerpStreetName>Gangsta Hideout</PerpStreetName>"
							"<PerpStreetType>ST</PerpStreetType>"
							"<PerpTown>Caulfield</PerpTown>"
							"<PerpState>VIC</PerpState>"
							"<PerpPostcode>3162</PerpPostcode>"
							"<PerpOtherAccomIn>true</PerpOtherAccomIn>"
							"<PoliceSpokenToPerpIn>false</PoliceSpokenToPerpIn>"
							"<FutureRiskCode>01</FutureRiskCode>"
							"<Court>Geelong Magistrates Court</Court>"
							"<CourtDt>2016-12-17T00:00:00</CourtDt>"
							"<FIPerpResidesWthAfmIn>true</FIPerpResidesWthAfmIn>"
							"<AFMLevelOfFearCode>02</AFMLevelOfFearCode>"    
							"<AfmResideCd>04</AfmResideCd>"
							"<PerpResideCd>01</PerpResideCd>"    
							"<AfmPrevIncidentNo>4</AfmPrevIncidentNo>"
							"<MostSeriousIncCd>1</MostSeriousIncCd>"    
							"<ExistingIntOrdsCd>1</ExistingIntOrdsCd>"
							//"<ReportTypeCode>FV</ReportTypeCode>"    
							//"<ReferralAction></ReferralAction>"
						"</ReportDetail>"
					"</ChildReferral>"
LAST);

	return 0;
}
